src/Entity/Client.php
<?php

namespace App\Entity;

use App\Repository\ClientRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ClientRepository::class)]
class Client
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $firstname = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $lastname = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $website = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $email = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $phone = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $address = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $company_name = null;

    #[ORM\Column(length: 255)]
    private ?string $state = null;

    #[ORM\ManyToOne(inversedBy: 'client')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $category = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(?string $firstname): static
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(?string $lastname): static
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getWebsite(): ?string
    {
        return $this->website;
    }

    public function setWebsite(?string $website): static
    {
        $this->website = $website;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): static
    {
        $this->phone = $phone;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): static
    {
        $this->address = $address;

        return $this;
    }

    public function getCompanyName(): ?string
    {
        return $this->company_name;
    }

    public function setCompanyName(?string $company_name): static
    {
        $this->company_name = $company_name;

        return $this;
    }

    public function getState(): ?string
    {
        return $this->state;
    }

    public function setState(string $state): static
    {
        $this->state = $state;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): static
    {
        $this->category = $category;

        return $this;
    }
}

src/Controller/ClientController.php
<?php

namespace App\Controller;

use App\Entity\Category;
use App\Entity\Client;
use App\Form\ClientFormType;
use App\Form\CSVFormType;
use App\Service\CSVReader;
use App\Service\DataManager;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class ClientController extends AbstractController
{

    #[Route('/clients/import', name: 'clients_import')]
    public function clientImport(Request $request, DataManager $dataManager): Response
    {
        $csvForm = $this->createForm(CSVFormType::class);
        $csvForm->handleRequest($request);

        if($csvForm->isSubmitted() && $csvForm->isValid()){
            $pathname = $csvForm['csv']->getData()->getPathName();
            $data = (new CSVReader)->readCSV($pathname);
            $dataManager->storeData($data);
        }

        return $this->render('clients/import.html.twig', [
            'csvForm' => $csvForm,
            'controller_name' => 'ClientController',
        ]);
    }

    #[Route('/clients', name:'clients_dashboard')]
    public function clientDashboard(EntityManagerInterface $entityManager):Response
    {
        $clients = $entityManager->getRepository(Client::class)->findAll();

        return $this->render('clients/dashboard.html.twig',[
            'clients' => $clients,
        ]);
    }

    #[Route('clients/{name}/add', name:'clients_add')]
    public function clientAdd(
        Category $category,
        EntityManagerInterface $entityManager,
        Request $request
    ):Response
    {
        $clientForm = $this->createForm(ClientFormType::class);
    
        $clientForm->handleRequest($request);

        if($clientForm->isSubmitted() && $clientForm->isValid()){
            $client = $clientForm->getData();
            $client->setCategory($category);
            $client->setState('Prospect');

            $entityManager->persist($client);
            $entityManager->flush();

            return $this->redirectToRoute('clients_category', ['name'=>$category->getName()]);
        }


        return $this->render('clients/add.html.twig', [
            'clientForm' => $clientForm
        ]);
    }

    #[Route('clients/update/{id}', name:'clients_update')]
    public function clientUpdate(
        Client $client,
        EntityManagerInterface $entityManager,
        Request $request
    ):Response
    {

        $clientForm = $this->createForm(ClientFormType::class, $client);

        $clientForm->handleRequest($request);

        if($clientForm->isSubmitted() && $clientForm->isValid()){
            $client = $clientForm->getData();

            $entityManager->flush();

            return $this->redirectToRoute('clients_category', ['name' => $client->getCategory()->getName()]);
        }


        return $this->render('clients/add.html.twig', [
            'clientForm' => $clientForm
        ]);
    }

    #[Route('clients/delete/{id}', name:'clients_delete')]
    public function clientsDelete(
        Client $client,
        Request $request,
        EntityManagerInterface $entityManager
    ):Response
    {

        $entityManager->remove($client);
        $entityManager->flush();

        return $this->redirectToRoute('clients_category', ['name' => $client->getCategory()->getName()]);
    }
}

templates/clients/add.html.twig
{% extends 'base.html.twig' %}

{% block title %} Dashboard {% endblock %}

{% block body %}


<h1>add</h1>

{{ form(clientForm)}}

{% endblock %}

templates/clients/dashboard.html.twig
{% extends 'base.html.twig' %}

{% block title %} Dashboard {% endblock %}

{% block body %}

{% if category|default %}
    <a href={{path('clients_add', {'name':category.name})}}>Ajouter</a>
{% endif %}

    <div class="clients">
    {% for client in clients %}
        <div class="client">
            <div class="client-info">{{client.companyName}}</div>
            <div class="client-info">{{client.firstname}}</div>
            <div class="client-info">{{client.lastname}}</div>
            <div class="client-info"><a href={{client.website}}>{{client.website}}</a></div>
            <div class="client-info">{{client.email}}</div>
            <div class="client-info">{{client.phone}}</div>
            <div class="client-info">{{client.address}}</div>
            <div class="client-info">{{client.state}}</div>
        </div>
        <div>
            <a href={{path('clients_update', {'id':client.id})}}>update</a>
            <a href={{path('clients_delete', {'id':client.id})}}>delete</a>
        </div>
    {% endfor %}
</div>

{% endblock %}

templates/clients/import.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ClientController!{% endblock %}

{% block body %}
{{ form(csvForm)}}
{% endblock %}

templates/clients/main.html.twig
{% extends 'base.html.twig' %}

{% block title %} Dashboard {% endblock %}

{% block body %}
<h1>Catégories</h1>
<div>
    <a href={{path('categories_add')}}>Créer une catégorie</a>
</div>

<div>
{% for category in categories %}
    <a href={{path('clients_category', {'name':category.name})}}>{{category.name}}</a>
    <a href={{path('categories_update', {'id':category.id})}}>update</a>
    <a href={{path('categories_delete', {'id':category.id})}}>delete</a>
{% endfor %}
</div>
{% endblock %}